server:
  port: 8080
spring:
  application:
    name: security
    index: ${random.int}
  profiles:
    active: dev
  datasource:
    tomcat:
      max-active: 60
      minIdle: 20
      initialSize: 30
    url: jdbc:mysql://localhost:3306/security
    name: security
    username: root
    password: root